"""
AutoFund Vault Position Monitor
================================
Watches Lido vault positions and delivers plain English alerts.
Tracks yield against benchmarks, detects allocation shifts,
and explains what changed and whether action is needed.

Built for The Synthesis Hackathon - Lido Vault Monitor Bounty ($1,500)
"""

import json
import time
from datetime import datetime, timedelta
from dataclasses import dataclass, field
from typing import Optional


@dataclass
class VaultSnapshot:
    """Point-in-time snapshot of vault state."""
    timestamp: str
    total_value_eth: float
    steth_apy: float
    benchmark_apy: float  # e.g., raw ETH staking or Aave
    yield_earned_24h: float
    allocation: dict  # protocol -> percentage


@dataclass
class Alert:
    """Alert generated by the monitor."""
    severity: str  # "info", "warning", "critical"
    title: str
    message: str
    action_required: bool
    timestamp: str


class VaultMonitor:
    """
    Monitors Lido Earn vault positions and generates human-readable alerts.

    Key features:
    - Tracks yield against external benchmarks
    - Detects allocation shifts across underlying protocols
    - Generates plain English explanations
    - Alerts on yield drops, unusual activity, or risk changes
    """

    def __init__(self):
        self.snapshots: list[VaultSnapshot] = []
        self.alerts: list[Alert] = []
        self.yield_floor: Optional[float] = None  # User-set minimum APY

        # Simulated current state
        self.current_state = VaultSnapshot(
            timestamp=datetime.utcnow().isoformat(),
            total_value_eth=50.0,
            steth_apy=3.5,
            benchmark_apy=3.2,
            yield_earned_24h=0.0048,
            allocation={
                "Aave": 35.0,
                "Morpho": 25.0,
                "Pendle": 20.0,
                "Gearbox": 12.0,
                "Maple": 8.0
            }
        )

    def set_yield_floor(self, min_apy: float):
        """Set minimum acceptable APY. Alert when breached."""
        self.yield_floor = min_apy
        return f"Yield floor set to {min_apy}%. You'll be alerted if APY drops below this."

    def take_snapshot(self) -> VaultSnapshot:
        """Capture current vault state."""
        snapshot = VaultSnapshot(
            timestamp=datetime.utcnow().isoformat(),
            total_value_eth=self.current_state.total_value_eth,
            steth_apy=self.current_state.steth_apy,
            benchmark_apy=self.current_state.benchmark_apy,
            yield_earned_24h=self.current_state.yield_earned_24h,
            allocation=dict(self.current_state.allocation)
        )
        self.snapshots.append(snapshot)
        return snapshot

    def check_yield_drop(self, current: VaultSnapshot, previous: Optional[VaultSnapshot]) -> Optional[Alert]:
        """Detect and explain yield drops."""
        if not previous:
            return None

        apy_change = current.steth_apy - previous.steth_apy
        if apy_change < -0.3:  # More than 0.3% drop
            return Alert(
                severity="warning",
                title="Yield Drop Detected",
                message=(
                    f"Your EarnETH yield dropped from {previous.steth_apy}% to {current.steth_apy}% "
                    f"(down {abs(apy_change):.2f}%). This is likely because Ethereum network activity "
                    f"decreased, reducing validator rewards across the network. "
                    f"Your position is still earning yield, just at a lower rate. "
                    f"Compared to raw ETH staking ({current.benchmark_apy}%), Lido still provides "
                    f"{'higher' if current.steth_apy > current.benchmark_apy else 'lower'} returns "
                    f"with the added benefit of liquidity."
                ),
                action_required=False,
                timestamp=datetime.utcnow().isoformat()
            )
        return None

    def check_yield_floor_breach(self, current: VaultSnapshot) -> Optional[Alert]:
        """Alert if yield drops below user-set floor."""
        if self.yield_floor and current.steth_apy < self.yield_floor:
            return Alert(
                severity="critical",
                title="Yield Below Your Floor",
                message=(
                    f"Current APY ({current.steth_apy}%) is below your minimum threshold "
                    f"of {self.yield_floor}%. You may want to consider rebalancing "
                    f"or adjusting your yield floor. Current alternatives: "
                    f"Aave supply ({current.benchmark_apy}%), rETH (~3.4%)."
                ),
                action_required=True,
                timestamp=datetime.utcnow().isoformat()
            )
        return None

    def check_allocation_shift(self, current: VaultSnapshot, previous: Optional[VaultSnapshot]) -> Optional[Alert]:
        """Detect significant allocation changes across protocols."""
        if not previous:
            return None

        shifts = []
        for protocol, pct in current.allocation.items():
            prev_pct = previous.allocation.get(protocol, 0)
            change = pct - prev_pct
            if abs(change) > 5:  # More than 5% shift
                direction = "increased" if change > 0 else "decreased"
                shifts.append(f"{protocol} {direction} from {prev_pct}% to {pct}%")

        if shifts:
            return Alert(
                severity="info",
                title="Vault Allocation Shift",
                message=(
                    f"The vault rebalanced its allocations: {'; '.join(shifts)}. "
                    f"This is normal behavior — the vault manager adjusts positions "
                    f"to optimize yield across underlying protocols. Your total position "
                    f"value is unaffected."
                ),
                action_required=False,
                timestamp=datetime.utcnow().isoformat()
            )
        return None

    def run_checks(self) -> list[Alert]:
        """Run all monitoring checks and return new alerts."""
        current = self.take_snapshot()
        previous = self.snapshots[-2] if len(self.snapshots) > 1 else None

        new_alerts = []

        checks = [
            self.check_yield_drop(current, previous),
            self.check_yield_floor_breach(current),
            self.check_allocation_shift(current, previous),
        ]

        for alert in checks:
            if alert:
                self.alerts.append(alert)
                new_alerts.append(alert)

        return new_alerts

    def generate_report(self) -> str:
        """Generate comprehensive plain English vault report."""
        current = self.current_state

        report = f"""
╔══════════════════════════════════════════════════════╗
║         VAULT POSITION MONITORING REPORT              ║
║         {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}                          ║
╚══════════════════════════════════════════════════════╝

YOUR POSITION:
  Total Value: {current.total_value_eth} ETH
  Current APY: {current.steth_apy}%
  24h Earnings: {current.yield_earned_24h:.4f} ETH (~${current.yield_earned_24h * 3500:.2f})
  {f'Yield Floor: {self.yield_floor}% {"✓ ABOVE" if current.steth_apy >= self.yield_floor else "⚠ BELOW"}' if self.yield_floor else 'Yield Floor: Not set'}

VAULT ALLOCATION:
"""
        for protocol, pct in current.allocation.items():
            bar = "█" * int(pct / 2) + "░" * (25 - int(pct / 2))
            report += f"  {protocol:12s} {bar} {pct:.1f}%\n"

        report += f"""
BENCHMARK COMPARISON:
  • Lido stETH:      {current.steth_apy}% APY  ← YOUR RATE
  • Raw ETH Staking: {current.benchmark_apy}% APY
  • Aave ETH Supply: 1.8% APY
  • rETH:            3.4% APY

  Verdict: You're earning {'MORE' if current.steth_apy > current.benchmark_apy else 'LESS'} than raw staking,
  with the added benefit of liquid staking (you can use stETH in DeFi).

RECENT ALERTS: {len(self.alerts)}
"""
        if self.alerts:
            for alert in self.alerts[-3:]:  # Show last 3
                icon = {"info": "ℹ️", "warning": "⚠️", "critical": "🚨"}.get(alert.severity, "•")
                report += f"  {icon} [{alert.severity.upper()}] {alert.title}\n"
                report += f"     {alert.message[:100]}...\n"
        else:
            report += "  None — everything looks normal ✓\n"

        report += f"""
WHAT TO DO:
  • No action needed — your position is performing as expected
  • Yield is {'above' if current.steth_apy > current.benchmark_apy else 'below'} the raw staking benchmark
  • Next report will be generated in 1 hour

STATUS: {'✓ ALL HEALTHY' if not any(a.severity == 'critical' for a in self.alerts) else '⚠ NEEDS ATTENTION'}
"""
        return report

    def format_telegram_alert(self, alert: Alert) -> str:
        """Format an alert for Telegram delivery."""
        icon = {"info": "ℹ️", "warning": "⚠️", "critical": "🚨"}.get(alert.severity, "•")
        action = "Action needed!" if alert.action_required else "No action needed."

        return f"""{icon} *AutoFund Vault Alert*

*{alert.title}*

{alert.message}

_{action}_
_Generated: {alert.timestamp}_"""


def demo():
    """Demo the vault monitor."""
    monitor = VaultMonitor()

    print("=== Vault Position Monitor Demo ===\n")

    # Set a yield floor
    print(monitor.set_yield_floor(3.0))

    # Generate initial report
    print(monitor.generate_report())

    # Simulate a yield drop
    print("\n--- Simulating yield drop ---")
    monitor.take_snapshot()  # Save current state
    monitor.current_state.steth_apy = 3.1  # Drop APY
    monitor.current_state.allocation["Aave"] = 30.0  # Shift allocation
    monitor.current_state.allocation["Morpho"] = 30.0

    alerts = monitor.run_checks()
    for alert in alerts:
        print(f"\n[{alert.severity.upper()}] {alert.title}")
        print(f"  {alert.message}")
        print(f"\n  Telegram format:")
        print(monitor.format_telegram_alert(alert))

    # Updated report
    print(monitor.generate_report())


if __name__ == "__main__":
    demo()
